  version: '3.8'
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_USER: movie_web_user 
        POSTGRES_DB: movie_web_backend 
        POSTGRES_PASSWORD: moviezRainbow1256
      ports:
        - "5432:5432" 
      networks:
        - sudo-flix-network
    sudo-flix:
      image: ghcr.io/sussy-code/backend:latest
      environment:
        MWB_POSTGRES__CONNECTION: postgresql://movie_web_user:moviezRainbow1256@postgres:5432/movie_web_backend
        MWB_CRYPTO__SESSION_SECRET: 32CharacterLongStringHere 
        MWB_META__NAME: rainbow_movies
        MWB_POSTGRES__MIGRATE_ON_BOOT: "true"
        MIKRO_ORM_MIGRATIONS_DISABLE_FOREIGN_KEYS: "true" 
      ports:
        - "80:80"
      depends_on:
        - postgres
      networks:
        - sudo-flix-network
  networks:
    sudo-flix-network: 
      driver: bridge